version: '3.9'

services:
  api:
    build: 
      target: development
    restart: 'no'
    volumes: 
      - ./api:/app
    ports: 
      - 8000:8000

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules # hack to not overwrite node_modules in container
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - REACT_APP_API_BASE_URL
  #     - REACT_APP_WS_BASE_URL
  #     - CHOKIDAR_USEPOLLING=true

  db:
    ports:
      - 5400:5432
