# Parameters under each service should be sorted alphabetically.

version: '3.9'

services:
  api:
    build: 
      context: ./api
      target: production
    restart: always
    depends_on:
      - celery
    command: sh -c "daphne --access-log /var/log/api/daphne/access.log --bind 0.0.0.0 core.asgi:application && python manage.py runworker -v2"
    volumes:
      - ./persistent_data/media:/var/lib/media
      - ./persistent_data/static:/var/lib/static
      - ./persistent_data/log/api/django:/var/log/api/django
      - ./persistent_data/log/api/daphne:/var/log/api/daphne
    env_file:
      - env_vars/.env_api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - ./persistent_data/media:/var/lib/media
      - ./persistent_data/static:/var/lib/static
      - ./persistent_data/log/nginx:/var/log/nginx/
    ports:
      - 1337:80
    depends_on:
      - api
    env_file:
      - env_vars/.env_frontend

  db:
    image: postgres:14.5
    restart: always
    volumes:
      - ./persistent_data/pg_data:/var/lib/postgresql/data
    env_file:
      - env_vars/.env_db

  celery:
    build: 
      context: ./api
      target: production
    restart: always
    depends_on:
      - db
      - redis
    command: celery --app tasks worker --loglevel WARNING
    volumes:
      - ./persistent_data/media:/var/lib/media
      - ./persistent_data/static:/var/lib/static
      - ./persistent_data/log/api/celery:/var/log/api/celery
    env_file:
      - env_vars/.env_api

  redis:
    image: redis:6.2-buster
    restart: always

  grafana:
    image: grafana/grafana:8.3.6
    volumes: 
      - ./persistent_data/grafana:/var/lib/grafana
    depends_on: 
      - prometheus

  prometheus:
    image: prom/prometheus:v2.33.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./persistent_data/prometheus:/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'

  proxy:
    build:
      context: ./proxy
    depends_on:
      - api
      - frontend
    env_file:
      - env_vars/.env_proxy
    ports:
      - 81:80
      - 444:443
    restart: always
    volumes:
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt

  certbot:
    build:
      context: ./certbot
    command: echo "Skipping..."
    depends_on:
      - proxy
    env_file:
      - env_vars/.env_certbot
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/

volumes:
  certbot-certs:
  certbot-web:
  proxy-dhparams:
